### ISSUE TITLE
Add String palindrome Snippet in any language

### ISSUE THREAD

**Issue by Anuja-19** [Anuja-19/Snippets#15]

**Comment by harikesh409** [comment]
I can do it can you assign it to me.

**Comment by Anuja-19** [comment]
Assigned it @harikesh409

**Comment by imyashl** [comment]
can you assign this to me?

**Comment by Anuja-19** [comment]
which language are you going to use @imyashl ?

**Comment by kaggrwal** [comment]
Can you assign it to me. I'll do it java/python/php.

**Comment by Anuja-19** [comment]
Assigning it to you @kaggrwal , do not do in python, it is already assigned for python. Please use java or php.

**Comment by kaggrwal** [comment]
Done, please merge https://github.com/Anuja-19/Snippets/pull/26

**Comment by mansijain014** [comment]
Please assign it to me I'll do it in C++

**Comment by arupam** [comment]
Can you assign it to me? I'll do it in Kotlin.

**Comment by ashishmishra95** [comment]
Hey Anuja,
I can help you with this in JavaScript want to give a try?

**Comment by Anuja-19** [comment]
Sure, @ashishmishra95  assigning you.

**Comment by Anuja-19** [comment]
@mansijain014  assigning you for cpp. Good luck!

**Comment by souvickroy02** [comment]
I would like to work on this issue. I will use C language to solve this issue. can you please assign me with this issue? Thank you.

**Comment by Anuja-19** [comment]
@souvickroy02 Assigning you

**Comment by ashish-garg18** [comment]
I would like to work on this. I can solve this using C, C++, python, Java

**Comment by ashish-garg18** [comment]
I would Like to Work on this. I can solve this using C, C++, Java, Javascript, Python . Can you assign it to me ?

**Comment by Anuja-19** [comment]
Hello, @ashish-garg18  this issue has already been assigned for the above said languages, please contribute to some other issue.

**Comment by souvickroy02** [comment]
why closed?
