### ISSUE TITLE
BFS & DFS Traversal | Algorithms | C++

### ISSUE THREAD

**Issue by SSKale1** [Anuja-19/Snippets#34]
## **`Breadth-First-Search and Depth-First-Search Traversal Algorithm`** 

I will be adding code for the BFS & DFS Traversal of an Undirected Graph

### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] C++

Please assign me this issue.

**Comment by Anuja-19** [comment]
Assigning you @SSKale1 , good luck!

**Comment by SSKale1** [comment]
Glad I could contribute.
