### ISSUE TITLE
Binary Search Tree in C

### ISSUE THREAD

**Issue by Eatbullets** [Anuja-19/Snippets#90]
Implement Binary Search Tree in any language

**Comment by vieee** [comment]
Hi, I would love to do this.. Could I..?

**Comment by Anuja-19** [comment]
@Eatbullets  assigning you for c

**Comment by Anuja-19** [comment]
@vieee  BST is already done for Java/C++/python. If you can implement in any other language, please let me know, I'll assign it to you.
